---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo add-apt-repository ppa:ansible/ansible
  - sudo apt-get install ansible
  - sudo apt-get update -qq

install:

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  - ansible-galaxy install willshersystems.apt

script:
  # Check the roles syntax
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Run the role
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - 'dpkg --status git >/dev/null'

